services:
  social-backend:
    image: registry.digitalocean.com/magnus-images/social:backend-0.2.4
    env_file: '.env'
    container_name: social-backend
    networks:
      - social-app
    restart: unless-stopped

networks:
  social-app:
    external: true
